
import "./globals.css";
import Header from "@/componentes/Header/header";
import Contatos from "@/componentes/Info/contatos";
import Footer from "@/componentes/footer/footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Header/>
        {children}
        <Contatos/>
        <Footer/>
      </body>
    </html>
  );
}
